project:
  type: website
  output-dir: _site

website:
  title: "Simen Bjerkelund"
  description: "Financial Analyst · Quantitative Researcher · Data Scientist"
  site-url: "https://simbje.github.io"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Data Projects"
        menu:
          - href: data-projects/index.qmd
            text: All Data Projects
          - href: data-projects/tennis-overview.qmd
            text: Tennis Statistics
      - text: "SSB Daily"
        href: ssb-daily/index.qmd
      - text: "Risk analysis and Machine Learning"
        href: https://simen-bjerkelund.shinyapps.io/tradingstats_shiny_app/
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/simen-bjerkelund-428b07141/
      - icon: github
        href: https://github.com/simbje
      - icon: envelope
        href: mailto:simbje@gmail.com




  page-footer:
    left: "© 2025 Simen Bjerkelund · Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light: [cosmo, assets/styles.scss]
    toc: true
    code-fold: true
    code-tools: true
    highlight-style: github

execute:
  freeze: auto   # only re-execute files that have changed
  echo: true
  warning: false
  message: false
  error: false   # don't halt entire render if one chunk errors
