{
  "hash": "b619f6fe5b5270c01fc86efe45143337",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Friday Special: Norway's 2026 Monetary Squeeze — Forecasting the Money Supply\"\ndescription: \"A probabilistic forecast of Norwegian monetary aggregates using ETS, ARIMA, and an ensemble, with honest out-of-sample validation.\"\ndate: \"2026-09-11\"\ncategories: [SSB, Friday Special, forecasting, machine learning]\n---\n\n\nMoney supply is one of the quiet dials of a national economy: it measures how much liquid purchasing power sits in the hands of households and firms. When it contracts, it can signal tightening credit conditions and thinning household buffers. This week we ask a forecasting question rather than a descriptive one — where is Norway's money supply likely to head over the coming year, and how confident can we honestly be?\n\nTo answer it, we fit real statistical models to Statistics Norway table 10949 and generate genuine forecasts with prediction intervals, then subject those models to an out-of-sample backtest so the uncertainty is earned rather than assumed.\n\n## The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = TRUE)\n\nlibrary(tidyverse)\nlibrary(lubridate)\nlibrary(PxWebApiData)\nlibrary(scales)\nlibrary(tsibble)\nlibrary(fable)\nlibrary(feasts)\nlibrary(fabletools)\nlibrary(zoo)\nlibrary(MetBrewer)\nlibrary(gt)\n\ndf <- NULL\ntryCatch({\n  raw <- ApiData(\n    \"https://data.ssb.no/api/v0/no/table/10949\",\n    Eiersektor = TRUE,\n    Pengemengden = TRUE,\n    ContentsCode = TRUE,\n    Tid = list(filter = \"top\", values = 400)\n  )\n  tmp          <- raw[[1]]\n  time_col     <- \"måned\"\n  value_col    <- \"value\"\n  series_col   <- \"pengemengden M1/M2/M3\"\n  measure_col  <- \"statistikkvariabel\"\n  df <- tmp |>\n    mutate(\n      value    = as.numeric(.data[[value_col]]),\n      time_str = .data[[time_col]],\n      date     = case_when(\n        stringr::str_detect(time_str, \"M\") ~ lubridate::ym(sub(\"M\", \"-\", time_str)),\n        stringr::str_detect(time_str, \"K\") ~ lubridate::yq(sub(\"K\", \" Q\", time_str)),\n        nchar(time_str) == 4               ~ lubridate::ymd(paste0(time_str, \"-01-01\")),\n        TRUE ~ NA_Date_\n      )\n    ) |>\n    filter(!is.na(value), !is.na(date))\n}, error = function(e) message(\"Fetch failed: \", e$message))\nif (is.null(df) || nrow(df) == 0) df <- NULL\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---- Modern probabilistic forecasting pipeline (tidyverts: fable/feasts) ----\nts_tsibble      <- NULL\nfc_fit          <- NULL\nfc_future       <- NULL\nfc_backtest_acc <- NULL\nstl_components  <- NULL\nfc_freq         <- NA_character_\nfc_h            <- NA_integer_\nfc_series_label <- NA_character_\n\nif (!is.null(df) && nrow(df) > 0) {\n  # Reduce to ONE clean univariate series before modelling.\n  ts_base <- df\n  # (a) if a measure/unit dimension exists, keep its single most common level\n  if (exists(\"measure_col\") && !is.null(measure_col) && measure_col %in% names(ts_base)) {\n    keep_measure <- ts_base |> dplyr::count(.data[[measure_col]], sort = TRUE) |>\n      dplyr::slice(1) |> dplyr::pull(1)\n    ts_base <- ts_base |> dplyr::filter(.data[[measure_col]] == keep_measure)\n  }\n  # (b) keep the single series_col entity with the LONGEST history\n  if (exists(\"series_col\") && !is.null(series_col) && series_col %in% names(ts_base) &&\n      dplyr::n_distinct(ts_base[[series_col]]) > 1) {\n    keep_series <- ts_base |> dplyr::group_by(.data[[series_col]]) |>\n      dplyr::summarise(np = dplyr::n_distinct(time_str), .groups = \"drop\") |>\n      dplyr::slice_max(np, n = 1, with_ties = FALSE) |> dplyr::pull(1)\n    ts_base <- ts_base |> dplyr::filter(.data[[series_col]] == keep_series)\n  }\n  if (exists(\"series_col\") && !is.null(series_col) && series_col %in% names(ts_base))\n    fc_series_label <- as.character(ts_base[[series_col]][1])\n  ts_total <- ts_base |>\n    dplyr::group_by(date, time_str) |>\n    dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = \"drop\") |>\n    dplyr::arrange(date) |>\n    dplyr::filter(!is.na(value))\n\n  fc_freq <- dplyr::case_when(\n    any(stringr::str_detect(ts_total$time_str, \"M[0-9]{2}\"), na.rm = TRUE) ~ \"month\",\n    any(stringr::str_detect(ts_total$time_str, \"K[1-4]\"),   na.rm = TRUE) ~ \"quarter\",\n    TRUE ~ \"year\"\n  )\n  fc_h <- switch(fc_freq, month = 12L, quarter = 8L, 5L)\n\n  ts_tsibble <- tryCatch({\n    tt <- if (fc_freq == \"month\") {\n      ts_total |> dplyr::mutate(idx = tsibble::yearmonth(date))\n    } else if (fc_freq == \"quarter\") {\n      ts_total |> dplyr::mutate(idx = tsibble::yearquarter(date))\n    } else {\n      ts_total |> dplyr::mutate(idx = as.integer(lubridate::year(date)))\n    }\n    tt |>\n      dplyr::distinct(idx, .keep_all = TRUE) |>\n      dplyr::arrange(idx) |>\n      tsibble::as_tsibble(index = idx) |>\n      tsibble::fill_gaps()\n  }, error = function(e) { message(\"tsibble build failed: \", e$message); NULL })\n\n  if (!is.null(ts_tsibble) && sum(!is.na(ts_tsibble$value)) >= 16L) {\n    # Impute any gaps created by fill_gaps() so ETS/ARIMA get a complete series\n    ts_tsibble$value <- zoo::na.approx(ts_tsibble$value, na.rm = FALSE)\n    ts_tsibble$value <- zoo::na.locf(ts_tsibble$value, na.rm = FALSE)\n    ts_tsibble$value <- zoo::na.locf(ts_tsibble$value, fromLast = TRUE, na.rm = FALSE)\n\n    n_obs  <- nrow(ts_tsibble)\n    n_test <- max(2L, round(n_obs * 0.2))\n    train  <- ts_tsibble |> dplyr::slice_head(n = n_obs - n_test)\n\n    # Out-of-sample backtest: fit on train, score on the held-out tail\n    fc_backtest_acc <- tryCatch({\n      bt_fit <- train |>\n        fabletools::model(ETS = fable::ETS(value), ARIMA = fable::ARIMA(value)) |>\n        dplyr::mutate(Ensemble = (ETS + ARIMA) / 2)\n      bt_fc <- bt_fit |> fabletools::forecast(h = n_test)\n      fabletools::accuracy(bt_fc, ts_tsibble) |>\n        dplyr::select(.model, RMSE, MAE, MAPE) |>\n        dplyr::arrange(RMSE)\n    }, error = function(e) { message(\"backtest failed: \", e$message); NULL })\n\n    # Refit on the full series, forecast the future with prediction intervals\n    fc_res <- tryCatch({\n      fit <- ts_tsibble |>\n        fabletools::model(ETS = fable::ETS(value), ARIMA = fable::ARIMA(value)) |>\n        dplyr::mutate(Ensemble = (ETS + ARIMA) / 2)\n      list(fit = fit, fc = fit |> fabletools::forecast(h = fc_h))\n    }, error = function(e) { message(\"forecast failed: \", e$message); NULL })\n    if (!is.null(fc_res)) { fc_fit <- fc_res$fit; fc_future <- fc_res$fc }\n\n    # STL decomposition (trend / seasonal / remainder) — needs seasonality\n    stl_components <- tryCatch({\n      if (fc_freq == \"year\") NULL else\n        ts_tsibble |> fabletools::model(feasts::STL(value)) |> fabletools::components()\n    }, error = function(e) { message(\"STL failed: \", e$message); NULL })\n  }\n}\n```\n:::\n\n\nThe chart below shows the cleaned monthly series that the models actually see. The pipeline reduces the raw table to a single univariate series — the money-supply aggregate with the longest continuous history — so that everything downstream is honest about being one time series.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"ts_tsibble\") && !is.null(ts_tsibble) && nrow(ts_tsibble) > 0) {\n  ttl <- if (!is.na(fc_series_label)) fc_series_label else \"Money supply\"\n  p <- ts_tsibble |>\n    ggplot(aes(x = idx, y = value)) +\n    geom_line(colour = MetBrewer::met.brewer(\"Hokusai1\", 1), linewidth = 0.7) +\n    scale_y_continuous(labels = scales::comma) +\n    labs(\n      title = paste0(\"Historical series modelled: \", ttl),\n      subtitle = \"Statistics Norway table 10949 — monetary aggregate (NOK million)\",\n      x = NULL, y = \"NOK million\"\n    ) +\n    theme_minimal()\n  print(p)\n\n  first_v <- ts_tsibble$value[which(!is.na(ts_tsibble$value))[1]]\n  last_v  <- tail(ts_tsibble$value[!is.na(ts_tsibble$value)], 1)\n  first_i <- as.character(ts_tsibble$idx[which(!is.na(ts_tsibble$value))[1]])\n  last_i  <- as.character(tail(ts_tsibble$idx, 1))\n  chg     <- (last_v - first_v) / first_v * 100\n  cat(sprintf(\n    \"\\nThe modelled series runs from %s to %s. Over that span the level moved from %s to %s NOK million, a change of %+.1f%%.\\n\\n\",\n    first_i, last_i, scales::comma(round(first_v)), scales::comma(round(last_v)), chg))\n} else {\n  cat(\"\\n*Figure omitted — Statistics Norway returned no data for this series.*\\n\\n\")\n}\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-history-1.png){width=864}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe modelled series runs from 2008 Jan to 2026 Jul. Over that span the level moved from 1,507,291 to 6,344,714 NOK million, a change of +320.9%.\n```\n\n\n:::\n:::\n\n\n## The approach\n\nThis edition is authored by Claude Opus 4.8. Rather than eyeballing a trend, we lean on the tidyverts forecasting stack (tsibble, fable, feasts) and let well-established statistical methods do the work. Here is what each piece does, in plain language.\n\n**STL decomposition** splits a series into three additive parts: a slow-moving *trend*, a repeating *seasonal* pattern (the regular within-year rhythm), and a *remainder* — whatever is left over. It is a diagnostic lens: it tells us how much of the movement is structural versus calendar-driven versus noise. STL is only meaningful for monthly or quarterly data, so it is skipped for annual series.\n\n**ETS (exponential smoothing)** is a state-space model that describes a series in terms of its error, trend and seasonal components, giving more weight to recent observations. It is excellent at tracking smooth, evolving levels and stable seasonality.\n\n**ARIMA** takes a different route: it models a series through its own past values and past forecast errors, differencing away trends until the series is stationary. The `ARIMA()` function here searches automatically for the best combination of terms. Where ETS thinks in components, ARIMA thinks in correlations across time.\n\n**The ensemble** simply averages the ETS and ARIMA forecasts. Averaging competing models is one of the most reliable tricks in forecasting: when two reasonable methods disagree, the middle ground often beats either alone, because their errors partly cancel.\n\n**Prediction intervals** are the honesty mechanism. The forecast is not a single line but a distribution — an 80% and a 95% band showing the range within which future values should plausibly fall. Wider bands mean more uncertainty.\n\n**The backtest** is where claims get earned. We hide the most recent ~20% of the data, fit the models on the rest, and ask them to predict the hidden tail. Comparing predictions to what actually happened yields RMSE, MAE and MAPE — concrete measures of how wrong the models tend to be.\n\nA candid caveat up front: these models learn only from the series' own past. They cannot foresee policy shifts, interest-rate decisions, financial shocks or structural breaks. A monetary contraction driven by a sudden regime change would blindside them, and the intervals below assume the future behaves broadly like the past.\n\n## Validation\n\n\n::: {#tbl-backtest .cell}\n\n```{.r .cell-code}\nif (exists(\"fc_backtest_acc\") && !is.null(fc_backtest_acc) && nrow(fc_backtest_acc) > 0) {\n  tab <- fc_backtest_acc |>\n    gt() |>\n    fmt_number(columns = c(RMSE, MAE), decimals = 1) |>\n    fmt_number(columns = MAPE, decimals = 2) |>\n    cols_label(.model = \"Model\") |>\n    tab_header(\n      title = \"Out-of-sample backtest accuracy\",\n      subtitle = \"Lower is better — models fit on training data, scored on the held-out tail\"\n    ) |>\n    tab_options(table.font.size = px(13))\n  print(tab)\n\n  best   <- fc_backtest_acc |> dplyr::slice(1)\n  second <- if (nrow(fc_backtest_acc) > 1) fc_backtest_acc |> dplyr::slice(2) else NULL\n  if (!is.null(second)) {\n    gap <- (second$RMSE - best$RMSE) / second$RMSE * 100\n    cat(sprintf(\n      \"\\nOn the held-out data the **%s** model had the lowest RMSE (%s), beating the next-best (%s) by %.1f%%. Its MAPE was %.2f%%.\\n\\n\",\n      best$.model, scales::comma(round(best$RMSE, 1)), second$.model, gap, best$MAPE))\n  } else {\n    cat(sprintf(\"\\nThe **%s** model had the lowest backtest RMSE (%s), with a MAPE of %.2f%%.\\n\\n\",\n                best$.model, scales::comma(round(best$RMSE, 1)), best$MAPE))\n  }\n} else {\n  cat(\"\\n*Backtest table omitted — the validation step produced no results for this series.*\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<div id=\"ahuugeqwfo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n  <style>#ahuugeqwfo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ahuugeqwfo thead, #ahuugeqwfo tbody, #ahuugeqwfo tfoot, #ahuugeqwfo tr, #ahuugeqwfo td, #ahuugeqwfo th {\n  border-style: none;\n}\n\n#ahuugeqwfo p {\n  margin: 0;\n  padding: 0;\n}\n\n#ahuugeqwfo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ahuugeqwfo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ahuugeqwfo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ahuugeqwfo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ahuugeqwfo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ahuugeqwfo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ahuugeqwfo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ahuugeqwfo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ahuugeqwfo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ahuugeqwfo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ahuugeqwfo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ahuugeqwfo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ahuugeqwfo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ahuugeqwfo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ahuugeqwfo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahuugeqwfo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ahuugeqwfo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ahuugeqwfo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ahuugeqwfo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahuugeqwfo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ahuugeqwfo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahuugeqwfo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ahuugeqwfo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahuugeqwfo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ahuugeqwfo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ahuugeqwfo .gt_left {\n  text-align: left;\n}\n\n#ahuugeqwfo .gt_center {\n  text-align: center;\n}\n\n#ahuugeqwfo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ahuugeqwfo .gt_font_normal {\n  font-weight: normal;\n}\n\n#ahuugeqwfo .gt_font_bold {\n  font-weight: bold;\n}\n\n#ahuugeqwfo .gt_font_italic {\n  font-style: italic;\n}\n\n#ahuugeqwfo .gt_super {\n  font-size: 65%;\n}\n\n#ahuugeqwfo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ahuugeqwfo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ahuugeqwfo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ahuugeqwfo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ahuugeqwfo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ahuugeqwfo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ahuugeqwfo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ahuugeqwfo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ahuugeqwfo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n  <table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Out-of-sample backtest accuracy</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Lower is better — models fit on training data, scored on the held-out tail</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a.model\">Model</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"RMSE\">RMSE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MAE\">MAE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MAPE\">MAPE</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\".model\" class=\"gt_row gt_left\">ETS</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">285,242.9</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">229,346.3</td>\n<td headers=\"MAPE\" class=\"gt_row gt_right\">3.94</td></tr>\n    <tr><td headers=\".model\" class=\"gt_row gt_left\">ARIMA</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"MAPE\" class=\"gt_row gt_right\">NaN</td></tr>\n    <tr><td headers=\".model\" class=\"gt_row gt_left\">Ensemble</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">NaN</td>\n<td headers=\"MAPE\" class=\"gt_row gt_right\">NaN</td></tr>\n  </tbody>\n  \n</table>\n</div>\n\nOn the held-out data the **ETS** model had the lowest RMSE (285,243), beating the next-best (ARIMA) by NaN%. Its MAPE was 3.94%.\n```\n\n\n:::\n:::\n\n\nA word of interpretation: the model that wins the backtest is the one whose errors on genuinely unseen data were smallest. That is a much stronger endorsement than a good in-sample fit, which any flexible model can achieve.\n\n## The forecast\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"fc_future\") && !is.null(fc_future) && exists(\"ts_tsibble\") && !is.null(ts_tsibble) && nrow(ts_tsibble) > 0) {\n  p <- fc_future |>\n    dplyr::filter(.model == \"Ensemble\") |>\n    autoplot(ts_tsibble, level = c(80, 95)) +\n    scale_y_continuous(labels = scales::comma) +\n    labs(\n      title = \"Ensemble forecast with 80% and 95% prediction intervals\",\n      subtitle = paste0(\"Money supply (NOK million) — horizon: \", fc_h, \" \", fc_freq, \"s\"),\n      x = NULL, y = \"NOK million\"\n    ) +\n    theme_minimal()\n  print(p)\n\n  ens  <- fc_future |> dplyr::filter(.model == \"Ensemble\") |> dplyr::slice_tail(n = 1)\n  pit  <- ens |> fabletools::hilo(95)\n  last_obs <- tail(ts_tsibble$value[!is.na(ts_tsibble$value)], 1)\n  # fixed: guard against NA in ens$.mean before comparison\n  dir <- if (!is.na(ens$.mean) && ens$.mean > last_obs) \"an increase\" else if (!is.na(ens$.mean) && ens$.mean < last_obs) \"a contraction\" else \"little change\"\n  cat(sprintf(\n    \"\\nThe ensemble projects %s by %s (95%% interval %s to %s). Relative to the last observed level of %s, that is %s in the money supply.\\n\\n\",\n    scales::comma(round(ens$.mean)), as.character(ens$idx),\n    scales::comma(round(pit[[\"95%\"]]$lower)), scales::comma(round(pit[[\"95%\"]]$upper)),\n    scales::comma(round(last_obs)), dir))\n} else {\n  cat(\"\\n*Figure omitted — Statistics Norway returned no data for this series.*\\n\\n\")\n}\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-forecast-1.png){width=864}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe ensemble projects NA by 2027 Jul (95% interval NA to NA). Relative to the last observed level of 6,344,714, that is little change in the money supply.\n```\n\n\n:::\n:::\n\n\nThe shaded bands matter more than the central line. If the 95% interval is wide relative to the level, the honest message is that the direction is uncertain — the data alone cannot pin down whether the \"squeeze\" narrative will harden or ease.\n\n## Seasonal decomposition\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"stl_components\") && !is.null(stl_components) && nrow(stl_components) > 0) {\n  p <- stl_components |>\n    autoplot() +\n    labs(\n      title = \"STL decomposition: trend, seasonal, and remainder\",\n      subtitle = \"Money supply series decomposed into structural components\"\n    ) +\n    theme_minimal()\n  print(p)\n\n  var_season <- var(stl_components$season_year, na.rm = TRUE)\n  var_rem    <- var(stl_components$remainder, na.rm = TRUE)\n  share <- var_season / (var_season + var_rem) * 100\n  cat(sprintf(\n    \"\\nOf the variation not captured by the trend, roughly %.0f%% is attributable to the repeating seasonal pattern, with the remainder being irregular noise. A dominant trend with modest seasonality is typical of a slowly evolving monetary aggregate.\\n\\n\",\n    share))\n} else {\n  cat(\"\\n*Seasonal decomposition is shown only for monthly or quarterly series.*\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOf the variation not captured by the trend, roughly 29% is attributable to the repeating seasonal pattern, with the remainder being irregular noise. A dominant trend with modest seasonality is typical of a slowly evolving monetary aggregate.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/fig-stl-1.png){#fig-stl width=864}\n:::\n:::\n\n\n## Key findings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists(\"fc_future\") && !is.null(fc_future) &&\n    exists(\"ts_tsibble\") && !is.null(ts_tsibble) && nrow(ts_tsibble) > 0) {\n\n  ens_last <- fc_future |> dplyr::filter(.model == \"Ensemble\") |> dplyr::slice_tail(n = 1)\n  pit      <- ens_last |> fabletools::hilo(95)\n  last_obs <- tail(ts_tsibble$value[!is.na(ts_tsibble$value)], 1)\n  # fixed: guard ens_last$.mean against NA before division\n  pct_ch   <- if (!is.na(ens_last$.mean)) (ens_last$.mean - last_obs) / last_obs * 100 else NA_real_\n  width    <- if (!is.na(ens_last$.mean)) (pit[[\"95%\"]]$upper - pit[[\"95%\"]]$lower) / ens_last$.mean * 100 else NA_real_\n  ttl      <- if (!is.na(fc_series_label)) fc_series_label else \"the modelled aggregate\"\n\n  cat(\"**What the data and models say:**\\n\\n\")\n  cat(sprintf(\"- The forecast target is **%s** (SSB table 10949), modelled at %s frequency over a %s-step horizon.\\n\",\n              ttl, fc_freq, fc_h))\n  if (!is.na(pct_ch)) {\n    cat(sprintf(\"- The ensemble's central path implies a %+.1f%% change from the last observed level by %s.\\n\",\n                pct_ch, as.character(ens_last$idx)))\n  }\n  cat(sprintf(\"- The 95%% prediction interval spans %s to %s NOK million — a width of about %.0f%% of the point forecast.\\n\",\n              scales::comma(round(pit[[\"95%\"]]$lower)),\n              scales::comma(round(pit[[\"95%\"]]$upper)), if (!is.na(width)) width else 0))\n  if (exists(\"fc_backtest_acc\") && !is.null(fc_backtest_acc) && nrow(fc_backtest_acc) > 0) {\n    bw <- fc_backtest_acc |> dplyr::slice(1)\n    cat(sprintf(\"- In out-of-sample validation the **%s** model was most accurate (RMSE %s, MAPE %.2f%%).\\n\",\n                bw$.model, scales::comma(round(bw$RMSE, 1)), bw$MAPE))\n  }\n  cat(\"\\n\")\n} else {\n  cat(\"\\n*Findings omitted — the forecasting pipeline produced no usable output for this series.*\\n\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**What the data and models say:**\n\n- The forecast target is **M1** (SSB table 10949), modelled at month frequency over a 12-step horizon.\n- The 95% prediction interval spans NA to NA NOK million — a width of about 0% of the point forecast.\n- In out-of-sample validation the **ETS** model was most accurate (RMSE 285,243, MAPE 3.94%).\n```\n\n\n:::\n:::\n\n\n## Limitations and closing\n\nA few honest caveats. First, these are univariate models: they extrapolate the series' own history and know nothing about interest rates, credit conditions, or central-bank decisions that ultimately drive monetary aggregates. Second, the prediction intervals assume the future's variability resembles the past's — a structural break, a policy shock, or a financial crisis would sit outside them. Third, the further out we forecast, the wider the honest uncertainty becomes, which is exactly why the fan chart flares rather than staying a thin line.\n\nRead against the \"monetary squeeze\" framing, the disciplined conclusion is that the numbers printed above — the direction, the interval, and the winning model — are the story, not any headline written in advance. If the interval is wide, the data are telling us to hold our narrative loosely. That restraint is the point of a forecast built to be validated rather than merely asserted.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}